triggers: perform static search only at the start of client QC moves
It's possible to come into contact with a trigger between the previous
move and the next, eg by spawning, teleporting, .solid change.  We won't
necessarily detect these while moving so for complete reliability we
must check before moving.

There's no need to check after moving as we hit any triggers we'd move
into contact with whilst performing the move.

Exception: MOVETYPE_PUSH might try to nudge a stuck entity which could
move it without calling _Movetype_PushEntity() so a search is still
performed if that happens.  Changed it to a less hacky code path.

This (and touching while moving) make it redundant for DP to call
SV_LinkEdict_TouchAreaGrid() in SV_Physics_ClientEntity().
That's the last place where DP calls touch funcs so they no longer need
the self global macros and their parameters may now be changed.

Also changed MOVETYPE_NOCLIP for clients to perform its own area grid
linking, like NOCLIP for other entities and other client movetypes.

If non-clients are using WALK or STEP they now perform the search first
like clients.